# Wine

### Introduction:

This exercise is a adaptation from the UCI Wine dataset.
The only pupose is to practice deleting data with pandas.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data).

### Step 3. Assign it to a variable called wine

In [5]:
wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data')
wine

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
173,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
174,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
175,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
176,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

### Step 4. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

In [7]:
wine.drop(columns=['1', '2.43', '2.8', '.28', '5.64', '3.92', '1065'], inplace=True)

### Step 5. Assign the columns as below:

The attributes are (donated by Riccardo Leardi, riclea '@' anchem.unige.it):  
1) alcohol  
2) malic_acid  
3) alcalinity_of_ash  
4) magnesium  
5) flavanoids  
6) proanthocyanins  
7) hue

In [8]:
wine.columns = ['alcohol', 'malic_acid', 'alcalinity_of_ash', 'magnesium',
                'flavanoids', 'proanthocyanins', 'hue']

### Step 6. Set the values of the first 3 rows from alcohol as NaN

In [9]:
wine.loc[0:2, 'alcohol'] = np.nan

### Step 7. Now set the value of the rows 3 and 4 of magnesium as NaN

In [11]:
wine.loc[3:4, 'magnesium'] = np.nan
wine

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.78,11.2,100.0,2.76,1.28,1.05
1,NaN,2.36,18.6,101.0,3.24,2.81,1.03
2,NaN,1.95,16.8,113.0,3.49,2.18,0.86
3,13.24,2.59,21.0,NaN,2.69,1.82,1.04
4,14.20,1.76,15.2,NaN,3.39,1.97,1.05
...,...,...,...,...,...,...,...
172,13.71,5.65,20.5,95.0,0.61,1.06,0.64
173,13.40,3.91,23.0,102.0,0.75,1.41,0.70
174,13.27,4.28,20.0,120.0,0.69,1.35,0.59
175,13.17,2.59,20.0,120.0,0.68,1.46,0.60
176,14.13,4.10,24.5,96.0,0.76,1.35,0.61

### Step 8. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

In [12]:
wine['alcohol'].fillna(10, inplace=True)
wine['magnesium'].fillna(100, inplace=True)

/tmp/ipython-input-12-553789278.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  wine['alcohol'].fillna(10, inplace=True)
/tmp/ipython-input-12-553789278.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  wine['magnesium'].fillna(100, inplace=True)

### Step 9. Count the number of missing values

In [13]:
print(wine.isna().sum())

alcohol              0
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### Step 10.  Create an array of 10 random numbers up until 10

In [14]:
rand_indices = np.random.randint(0, len(wine), 10)
print(rand_indices)

[ 24 160 154  90 128  23 151  76 146  31]

### Step 11.  Use random numbers you generated as an index and assign NaN value to each of cell.

In [15]:
for i in rand_indices:
    wine.loc[i, 'hue'] = np.nan

### Step 12.  How many missing values do we have?

In [16]:
print(wine.isna().sum().sum())

10

### Step 13. Delete the rows that contain missing values

In [17]:
wine.dropna(inplace=True)

### Step 14. Print only the non-null values in alcohol

In [18]:
print(wine['alcohol'].dropna())

0      10.00
1      10.00
2      10.00
3      13.24
4      14.20
       ...
172    13.71
173    13.40
174    13.27
175    13.17
176    14.13
Name: alcohol, Length: 167, dtype: float64

### Step 15.  Reset the index, so it starts with 0 again

In [19]:
wine.reset_index(drop=True, inplace=True)

### BONUS: Create your own question and answer it.

In [20]:
#  What is the average flavanoids value in the cleaned data?
print("Average flavanoids:", wine['flavanoids'].mean())

Average flavanoids: 2.0522754491017965